# Generated by Django 4.2.11 on 2024-04-01 19:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.date.today, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "number",
                    models.CharField(
                        help_text="Version number of the App. Usually formatted as v1.0",
                        max_length=64,
                        verbose_name="number",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Version approved?"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.date.today, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("description", models.TextField(blank=True)),
                ("repo_url", models.CharField(max_length=300, verbose_name="repo URL")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.version"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
