# Generated by Django 4.2.11 on 2024-04-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="version",
        ),
        migrations.AddField(
            model_name="version",
            name="app",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="apps.app"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.CharField(
                help_text="Version number of an App. Usually formatted as v1.0",
                max_length=64,
                verbose_name="number",
            ),
        ),
    ]
