# Generated by Django 4.2.11 on 2024-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesx", "0003_remove_site_ip_address_remove_site_username_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="ip_address",
            field=models.CharField(help_text="IPv4 address", max_length=16),
        ),
        migrations.AlterField(
            model_name="instance",
            name="username",
            field=models.CharField(help_text="Username for ssh access", max_length=50),
        ),
    ]
