# Generated by Django 4.2.11 on 2024-04-01 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sitesx", "0005_delete_instance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="lead",
        ),
        migrations.AddField(
            model_name="district",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
