# Generated by Django 4.2.11 on 2024-04-01 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sitesx", "0006_remove_zone_lead_district_contact_zone_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="site",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="zone",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
