# Generated by Django 4.2.11 on 2024-04-01 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesx", "0007_site_created_at_site_created_by_site_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="district",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="site",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="updated at"),
        ),
    ]
