# Generated by Django 4.2.11 on 2024-04-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0002_cluster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="instance",
            name="created_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
