# Generated by Django 4.2.11 on 2024-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0003_alter_cluster_created_at_alter_instance_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="instance",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="instance",
            name="ip_address",
            field=models.CharField(
                help_text="IPv4 address", max_length=16, verbose_name="IP address"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="instance",
            name="username",
            field=models.CharField(
                help_text="Username for ssh access",
                max_length=50,
                verbose_name="username",
            ),
        ),
    ]
