# Generated by Django 4.2.11 on 2024-04-01 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instances", "0004_alter_cluster_description_alter_cluster_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="instance",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="updated at"),
        ),
    ]
