# Generated by Django 4.2.11 on 2024-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "instances",
            "0005_alter_cluster_created_at_alter_cluster_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cluster",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="instance",
        ),
        migrations.AlterField(
            model_name="instance",
            name="username",
            field=models.CharField(
                help_text="Username for SSH access",
                max_length=50,
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="instance",
            field=models.ManyToManyField(to="instances.instance"),
        ),
    ]
